version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py migrate && python manage.py setup_faker && gunicorn config.wsgi:application --bind 0.0.0.0:8000 --timeout 120 --workers=3 --threads=3 --worker-connections=1000"
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      db :
        condition: service_healthy
    links:
      - db

volumes:
  postgres_data:
